### PR TITLE
Implement backend support for azure

### PR DESCRIPTION
**Pull request by jeppester**
In order to deploy this we'll need to build the new image with the following new env vars set in `.env.docker`:

```
AI_PROVIDER=openai-azure
OPENAI_AZURE_ENDPOINT=[our azure endpoint]
OPENAI_AZURE_KEY=[our azure key]
OPENAI_AZURE_VERSION=2023-05-15
DEFAULT_CHAT_MODEL="gpt-4o"
DEFAULT_EMBEDDINGS_MODEL="text-embedding-ada-002"
```

### CODE REVIEW

**Comment by runephilosof-abtion** [comment]
It makes sense to also make a PR to upstream with this, right?

**Comment by jeppester** [comment]
> It makes sense to also make a PR to upstream with this, right?

I made the code so that it can be expanded to let the user select azure in the frontend, but I have not implemented it (since it doesn't matter to us).

Unfortunately it's not only a matter of selecting another token, we also need to change how to select the models for embeddings and chat when azure is used.

You can currently break things by selecting a model in the frontend (currently the selection is hardcoded) that the azure endpoint does not have provisioned.

For those reasons the changes we've made feels only half-done, and it doesn't make much sense for us to do the other half.

Still we could make a PR and see what the webwhiz folks say about it :thinking:

**Comment by runephilosof-abtion** [comment]
We want to avoid having to maintain differences to upstream, so in that sense it does make sense to do extra work to get it merged upstream.
However, they have not reacted to our other PRs, so maybe we should wait and see.

**Comment by hcarreras** [comment]
Agree with wait and see. We also need to wait to see how much dao wants to keep investing in this. This is supposed to be a MVP.

**Pull request merged**
